#!/usr/bin/env ruby

# This file is part of Horologist.
# (c) Jesus Leon <git@jes.mx>
# For the full copyright and license information, please view 
# the LICENSE file that was distributed with this source code.
